# Task Name: (Required) 
task_name: 'AYDO Koii Myst Task'
# Task Author: (Required) 
author: 'AYDO Ltd.'
# Task Description: (Required) 
description: "The AYDO Koii Myst Task is a decentralized task that leverages the Mysterium Network to provide secure, private, and decentralized VPN services. This task allows users to run Mysterium nodes, earn rewards, and contribute to a global network of privacy-focused infrastructure. By participating in this task, users help maintain a robust and censorship-resistant VPN network, ensuring privacy and security for users worldwide. The task rewards node operators for their contribution to the network's reliability and performance, fostering a sustainable ecosystem for decentralized VPN services."

markdownDescriptionPath: './TaskDescription.md'

# Repository URL: (Required)
repositoryUrl: 'https://github.com/AYDOAI/aydo-koii-myst-task' 
# Image URL: (Required) Will be displayed in desktop node
imageUrl: 'https://cdn.prod.website-files.com/65f6f8696e3e74cc79b99495/6620cc99263244d81f65f8aa_MystNodes%20landingpage%20logo%20(1).svg'
# Info URL: (Required) Will be displayed in desktop node
infoUrl: 'https://www.mystnodes.com/'

# Task executable network: (Required | DEVELOPMENT, ARWEAVE, or IPFS) : IPFS is the default and common value
task_executable_network: 'IPFS'

# Task audit program: (Required) IPFS: Path to your executable | DEVELOPMENT: Leave it as 'main'
task_audit_program: 'dist/main.js'

# Round time: (Required) Duration of task, measured in slots (with each slot approximately equal to 408ms).
round_time: 1200

# Audit window: (Required) The audit window should be greater than 1/3 of the round time.
audit_window: 500

# Submission window: (Required) The submission window should be greater than 1/3 of the round time.
submission_window: 500

# Minimum stake amount: (Required) The minimum amount of KOII that a user must stake in order to participate in the task.
minimum_stake_amount: 1.9

# Task Bounty Type: (Required | KOII or KPL) 
task_type: 'KOII'

# Token Mint Address: (ONLY task_type == KPL) Fire Token as an example here. 
token_type: "4qayyw53kWz6GzypcejjT1cvwMXS1qYLSMQRE8se3gTv"

# Total bounty amount:  (Required) The total bounty amount that will be distributed to the task. (Not accepted in case of update task).
total_bounty_amount: 0

# Bounty amount per round: (Required) Every round's maximum distribution, you can decide the logics in your task. 
bounty_amount_per_round: 0

# Allowed failed distributions: (Required) Number of times re-submission is allowed for the distribution list in case of an audit, it is also the rounds of submission it will keep. 
allowed_failed_distributions: 3

# Space: (Required) Expected Task Data Size in MBs for the account size. 
# Minimum: 1 for production, 0.1 for testing; Calculation Details: https://www.koii.network/docs/develop/command-line-tool/create-task-cli/create-task#space
space: 0.1

# Requirement Tags: (Optional): To add more global variables and task variables, please refer to the type, value, description format shown below.
requirementsTags:
  - type: ADDON
    value: 'ORCA_TASK'
  - type: CPU
    value: '4-core'
  - type: RAM
    value: '5 GB'
  - type: STORAGE
    value: '5 GB'
  - type: TASK_VARIABLE
    value: 'BENEFICIARY_WALLET'
    description: 'Your earnings will automatically be paid out to the wallet address submitted below. If you have not set your wallet or would like to update it, please do it now. Please make sure the address an ERC-20 Polygon compatible wallet e.g. MetaMask'

# Tags: You can select the tags here via https://www.koii.network/docs/develop/command-line-tool/create-task-cli/create-task#tags
tags: ["VPN", "Network", "Decentralized"] 
# Environment: (Required | TEST or PRODUCTION) Production mode will expose your task to all the task runners. 
environment: "PRODUCTION"

#################################### BELOW IS FOR UPDATE TASK ONLY ####################################
# Old Task ID: (ONLY for task update) 
task_id: ''

# Migration Description: (ONLY for task update)
migrationDescription: ''
